name: "Data Louna"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"

  app:
    build: .
    restart: on-failure
    container_name: app
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  db: